### ISSUE TITLE
Auto refresh for GECKOPRICE?

### ISSUE THREAD

**Issue by jdx-john** [Eloise1988/COINGECKO#15]
Hi,

I see that this function mentions taking different parameters but every combination is not clear to me.
Most importantly there is mention of an optional 3rd parameter 'refresh cell'. This isn't shown as an option when I enter the formula in a google-sheet, and I'm not sure how it works because in examples it seems to point to empty cells.

I have my sheet set to recalculate values on change, so is it possible to make my sheet automatically re-run GECKO calls every X minutes, or perhaps to add/mock a button-press? If you can give a concrete example this would be appreciated.

**Comment by Eloise1988** [comment]
![prices_array_refresh](https://user-images.githubusercontent.com/53000607/118163405-3968f680-b422-11eb-994d-0e680a50d094.gif)

In the gif you can see how it works. The third parameter is set to a dummy cell in the sheet. In this case, it's b10. Each time I change the value in b10, it will refresh the formula that reference to cell B10. In our case it's refreshes the GECKOPRICES.

FYI:
There is 10min caching in the sheet because of Coingecko's and Google Sheet API limitations.
