### ISSUE TITLE
IOT ticker not working

### ISSUE THREAD

**Issue by ericmoret** [Eloise1988/COINGECKO#21]
Receiving the following error for ticker: IOT

`{"error":"Could not find coin with the given id"} (line 0).`

**Comment by Eloise1988** [comment]
Hi Eric,

#faq Coingecko Ticker duplicates

There is no existing IOT ticker.. Did you mean IOTX?

Sometimes when multiple projects have the same ticker, the GECKOPRICE() function doesn't work properly.
Instead you need to use the "ID" name instead of ticker. 

In order to find the ID, you need to search in the following coingecko id page:
https://api.coingecko.com/api/v3/search?locale=fr&img_path_only=1

For more information, check the following medium and search for GECKOPRICEBYNAME 
https://medium.com/the-cryptocurious/coingecko-prices-volumes-market-caps-in-google-sheets-and-excel-a1a3ee201cb8
