### ISSUE TITLE
Refresh Interval for GECKOPRICEBYNAME

### ISSUE THREAD

**Issue by DanitiKain** [Eloise1988/COINGECKO#25]
The refresh interval in the documentation doesn't say how often the data is refreshed meaning what is the time interval. If I put in 10 is that 10 minutes, 10 days or 10 weeks?

**Comment by Eloise1988** [comment]
Hi,


![telegram-cloud-photo-size-4-5864015868701291835-y](https://user-images.githubusercontent.com/53000607/140527538-382f6979-36f1-4cd1-a381-b19c360f0af6.jpg)

By default, as shown on the above picture the cache is 10 minutes (600 seconds).

If you wish to lower it, you can change it manually. For example if you wish for 1min, you would need to put 60 instead of the 600 seconds.

Sorry I didn't define it in the code, I will add a comment in the future code versions. Thank you.

**Comment by DanitiKain** [comment]
ok now if you manually set it in the syntax states - Syntax: GECKOPRICEBYNAME(id_coin, currency,[optional refresh attribute])


what is the "optional refresh attribute" timer value minutes, days, weeks, years?

**Comment by Eloise1988** [comment]
The optional cell is when you want to refresh group of formulas at the same time, it's not linked to the refresh timing.
Let's say the optional refresh cell is A1, each time you modify the value in A1, it will load all formulas that are linked to cell A1 as the optional refresh attribute

**Comment by Eloise1988** [comment]
Cell M11 acts as the refreshing cell 

![refresh_optionalcell](https://user-images.githubusercontent.com/53000607/140531416-a953e627-9e56-41c4-bcaa-a259f017e2f7.gif)
