### ISSUE TITLE
Wrong price's for some Token's

### ISSUE THREAD

**Issue by EktorBaboden** [Eloise1988/COINGECKO#34]
Hi thanks for sharing this great script

I having issue for this token's price, is delivering me zero or wrong price.
Jade Protocol JADE
Hector DAO HEC
Town Star TOWN
Atlantis ATLAS
Bombcrypto BCOIN
GalaxyGoggle DAO GG

Can you help me solve this?

**Comment by Eloise1988** [comment]
#faq Coingecko Ticker duplicates

Sometimes when multiple projects have the same ticker, the GECKOPRICE() function doesn't work.
Instead of using the ticker you can request the price with the "ID". 
In order to find the ID, you need to search in the following coingecko id page:
https://api.coingecko.com/api/v3/search?locale=fr&img_path_only=1

**Comment by dadaas** [comment]
Yea, it works. ID works by using coingeckopricebyname
But is there a way to remove ticker and use ID, because lots of problems by using ricker. I use 10 coins and 6 of them need to use ID because they have same ticker or ticker is even not working. For example THG for thetan Arena, it is unique but is not working, however  ID is working perfectly fine...

**Comment by Eloise1988** [comment]
@dadaas 
I rewrote the code of the geckopricebyname function.
Now you can request an array of data using solely the coingecko api ids as shown on the below image.

<img width="479" alt="image" src="https://user-images.githubusercontent.com/53000607/161437811-4eac79fc-5b90-4c7f-9de1-52fd0edaaa00.png">

You can find the new code here :
https://raw.githubusercontent.com/Eloise1988/COINGECKO/master/CoinGeckoV2.gs

Hope that helps with the ticker & coingecko id interference experienced with the geckoprice function.

**Comment by dadaas** [comment]
Yes, that fixes most of the issues with duplicate coins. Anyway coingecko also prefers the usage of IDs, they even have them on their website as a button for quick copy paste...

**Comment by dadaas** [comment]
Is there a chance that this: market_data/price_change_percentage_7d_in_currency/usd and this: market_data/price_change_percentage_30d_in_currency/usd work with ID and not ticker?

I think it would be best that the whole tool switches to ID because of the problems with tickers.
