### ISSUE TITLE
Currency Code Mismatch

### ISSUE THREAD

**Issue by jpfieber** [Eloise1988/COINGECKO#7]
I earned some "Celo" through Coinbase, which assigns it the currency code "CGLD". The GECKOPRICE formula I setup that looks at activity I exported from Coinbase worked for all my other assets, but failed for CGLD. I searched CoinGecko and they list it's currency code as "CELO". Is there a way you could add a way of dealing with this type of mismatch?

**Comment by Eloise1988** [comment]
Hi,

You have to call the price of CELO directly without the reference of CGLD since it doesn't exist as a ticker.
You could write something like:

=if(A1="CGLD", GECKOPRICE("CELO","USD"),GECKOPRICE(A1,"USD"))

This formula will check if Coinbase's ticker is CGLD and if so, will get the price of CELO on Coingecko, if not it gets the price of the ticker in the reference cell.

Hopes this helps,

**Comment by jpfieber** [comment]
If I had a lot of different currencies with issue that might get unwieldy,
but I don't anticipate that happening so this seems like a good solution.
Thanks for the solution, and thanks for the great tool you put together!
